import { AirportInfo } from '@/types/flight';

export const AIRPORTS: Record<string, AirportInfo> = {
  // Sân bay Việt Nam
  HAN: {
    iata: 'HAN',
    icao: 'VVNB',
    name: 'Sân bay Quốc tế Nội Bài',
    city: 'Hà Nội',
    country: 'Việt Nam',
    lat: 21.2212,
    lon: 105.8072,
    timezone: 'Asia/Ho_Chi_Minh',
  },
  SGN: {
    iata: 'SGN',
    icao: 'VVTS',
    name: 'Sân bay Quốc tế Tân Sơn Nhất',
    city: 'TP. Hồ Chí Minh',
    country: 'Việt Nam',
    lat: 10.8188,
    lon: 106.6519,
    timezone: 'Asia/Ho_Chi_Minh',
  },
  DAD: {
    iata: 'DAD',
    icao: 'VVDN',
    name: 'Sân bay Quốc tế Đà Nẵng',
    city: 'Đà Nẵng',
    country: 'Việt Nam',
    lat: 16.0439,
    lon: 108.1994,
    timezone: 'Asia/Ho_Chi_Minh',
  },
  CXR: {
    iata: 'CXR',
    icao: 'VVCR',
    name: 'Sân bay Quốc tế Cam Ranh',
    city: 'Khánh Hòa / Nha Trang',
    country: 'Việt Nam',
    lat: 11.9981,
    lon: 109.2194,
    timezone: 'Asia/Ho_Chi_Minh',
  },
  PQC: {
    iata: 'PQC',
    icao: 'VVPQ',
    name: 'Sân bay Quốc tế Phú Quốc',
    city: 'Phú Quốc / Kiên Giang',
    country: 'Việt Nam',
    lat: 10.1698,
    lon: 103.9931,
    timezone: 'Asia/Ho_Chi_Minh',
  },
  HPH: {
    iata: 'HPH',
    icao: 'VVCI',
    name: 'Sân bay Quốc tế Cát Bi',
    city: 'Hải Phòng',
    country: 'Việt Nam',
    lat: 20.8192,
    lon: 106.7247,
    timezone: 'Asia/Ho_Chi_Minh',
  },
  VDO: {
    iata: 'VDO',
    icao: 'VVVD',
    name: 'Sân bay Quốc tế Vân Đồn',
    city: 'Quảng Ninh',
    country: 'Việt Nam',
    lat: 21.1197,
    lon: 107.4144,
    timezone: 'Asia/Ho_Chi_Minh',
  },
  VII: {
    iata: 'VII',
    icao: 'VVVH',
    name: 'Sân bay Quốc tế Vinh',
    city: 'Nghệ An',
    country: 'Việt Nam',
    lat: 18.7375,
    lon: 105.6708,
    timezone: 'Asia/Ho_Chi_Minh',
  },
  HUI: {
    iata: 'HUI',
    icao: 'VVPB',
    name: 'Sân bay Quốc tế Phú Bài',
    city: 'Huế',
    country: 'Việt Nam',
    lat: 16.4017,
    lon: 107.7031,
    timezone: 'Asia/Ho_Chi_Minh',
  },
  VCA: {
    iata: 'VCA',
    icao: 'VVCT',
    name: 'Sân bay Quốc tế Cần Thơ',
    city: 'Cần Thơ',
    country: 'Việt Nam',
    lat: 10.0853,
    lon: 105.7119,
    timezone: 'Asia/Ho_Chi_Minh',
  },
  DLI: {
    iata: 'DLI',
    icao: 'VVDL',
    name: 'Sân bay Liên Khương',
    city: 'Đà Lạt / Lâm Đồng',
    country: 'Việt Nam',
    lat: 11.7503,
    lon: 108.3739,
    timezone: 'Asia/Ho_Chi_Minh',
  },
  UIH: {
    iata: 'UIH',
    icao: 'VVPC',
    name: 'Sân bay Phù Cát',
    city: 'Quy Nhơn / Bình Định',
    country: 'Việt Nam',
    lat: 13.9553,
    lon: 109.0422,
    timezone: 'Asia/Ho_Chi_Minh',
  },
  BMV: {
    iata: 'BMV',
    icao: 'VVBM',
    name: 'Sân bay Buôn Ma Thuột',
    city: 'Đắk Lắk',
    country: 'Việt Nam',
    lat: 12.6681,
    lon: 108.1203,
    timezone: 'Asia/Ho_Chi_Minh',
  },
  PXU: {
    iata: 'PXU',
    icao: 'VVPK',
    name: 'Sân bay Pleiku',
    city: 'Gia Lai',
    country: 'Việt Nam',
    lat: 14.0044,
    lon: 108.0169,
    timezone: 'Asia/Ho_Chi_Minh',
  },
  THD: {
    iata: 'THD',
    icao: 'VVTX',
    name: 'Sân bay Thọ Xuân',
    city: 'Thanh Hóa',
    country: 'Việt Nam',
    lat: 19.9017,
    lon: 105.4678,
    timezone: 'Asia/Ho_Chi_Minh',
  },
  VDH: {
    iata: 'VDH',
    icao: 'VVDH',
    name: 'Sân bay Đồng Hới',
    city: 'Quảng Bình',
    country: 'Việt Nam',
    lat: 17.5153,
    lon: 106.5908,
    timezone: 'Asia/Ho_Chi_Minh',
  },
  DIN: {
    iata: 'DIN',
    icao: 'VVDB',
    name: 'Sân bay Điện Biên Phủ',
    city: 'Điện Biên',
    country: 'Việt Nam',
    lat: 21.3972,
    lon: 103.0078,
    timezone: 'Asia/Ho_Chi_Minh',
  },
  VCS: {
    iata: 'VCS',
    icao: 'VVCS',
    name: 'Sân bay Côn Đảo',
    city: 'Bà Rịa - Vũng Tàu',
    country: 'Việt Nam',
    lat: 8.7328,
    lon: 106.6292,
    timezone: 'Asia/Ho_Chi_Minh',
  },
  VKG: {
    iata: 'VKG',
    icao: 'VVRG',
    name: 'Sân bay Rạch Giá',
    city: 'Kiên Giang',
    country: 'Việt Nam',
    lat: 9.9597,
    lon: 105.1342,
    timezone: 'Asia/Ho_Chi_Minh',
  },
  TBB: {
    iata: 'TBB',
    icao: 'VVTH',
    name: 'Sân bay Tuy Hòa',
    city: 'Phú Yên',
    country: 'Việt Nam',
    lat: 13.0489,
    lon: 109.3339,
    timezone: 'Asia/Ho_Chi_Minh',
  },
  VCL: {
    iata: 'VCL',
    icao: 'VVCA',
    name: 'Sân bay Chu Lai',
    city: 'Quảng Nam',
    country: 'Việt Nam',
    lat: 15.4061,
    lon: 108.7056,
    timezone: 'Asia/Ho_Chi_Minh',
  },

  // Sân bay Quốc tế Khu vực & Thế giới
  BKK: {
    iata: 'BKK',
    icao: 'VTBS',
    name: 'Sân bay Quốc tế Suvarnabhumi',
    city: 'Bangkok',
    country: 'Thái Lan',
    lat: 13.6900,
    lon: 100.7501,
    timezone: 'Asia/Bangkok',
  },
  DMK: {
    iata: 'DMK',
    icao: 'VTBD',
    name: 'Sân bay Quốc tế Don Mueang',
    city: 'Bangkok',
    country: 'Thái Lan',
    lat: 13.9125,
    lon: 100.6067,
    timezone: 'Asia/Bangkok',
  },
  SIN: {
    iata: 'SIN',
    icao: 'WSSS',
    name: 'Sân bay Quốc tế Changi',
    city: 'Singapore',
    country: 'Singapore',
    lat: 1.3644,
    lon: 103.9915,
    timezone: 'Asia/Singapore',
  },
  KUL: {
    iata: 'KUL',
    icao: 'WMKK',
    name: 'Sân bay Quốc tế Kuala Lumpur',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    lat: 2.7456,
    lon: 101.7099,
    timezone: 'Asia/Kuala_Lumpur',
  },
  ICN: {
    iata: 'ICN',
    icao: 'RKSI',
    name: 'Sân bay Quốc tế Incheon',
    city: 'Seoul / Incheon',
    country: 'Hàn Quốc',
    lat: 37.4602,
    lon: 126.4407,
    timezone: 'Asia/Seoul',
  },
  NRT: {
    iata: 'NRT',
    icao: 'RJAA',
    name: 'Sân bay Quốc tế Narita',
    city: 'Tokyo / Narita',
    country: 'Nhật Bản',
    lat: 35.7647,
    lon: 140.3863,
    timezone: 'Asia/Tokyo',
  },
  HND: {
    iata: 'HND',
    icao: 'RJTT',
    name: 'Sân bay Quốc tế Haneda',
    city: 'Tokyo',
    country: 'Nhật Bản',
    lat: 35.5494,
    lon: 139.7798,
    timezone: 'Asia/Tokyo',
  },
  KIX: {
    iata: 'KIX',
    icao: 'RJBB',
    name: 'Sân bay Quốc tế Kansai',
    city: 'Osaka',
    country: 'Nhật Bản',
    lat: 34.4347,
    lon: 135.2442,
    timezone: 'Asia/Tokyo',
  },
  HKG: {
    iata: 'HKG',
    icao: 'VHHH',
    name: 'Sân bay Quốc tế Hong Kong',
    city: 'Hong Kong',
    country: 'Hồng Kông',
    lat: 22.3080,
    lon: 113.9185,
    timezone: 'Asia/Hong_Kong',
  },
  TPE: {
    iata: 'TPE',
    icao: 'RCTP',
    name: 'Sân bay Quốc tế Đào Viên',
    city: 'Đài Bắc / Đào Viên',
    country: 'Đài Loan',
    lat: 25.0797,
    lon: 121.2342,
    timezone: 'Asia/Taipei',
  },
  CAN: {
    iata: 'CAN',
    icao: 'ZGGG',
    name: 'Sân bay Quốc tế Bạch Vân Quảng Châu',
    city: 'Quảng Châu',
    country: 'Trung Quốc',
    lat: 23.3924,
    lon: 113.2988,
    timezone: 'Asia/Shanghai',
  },
  PEK: {
    iata: 'PEK',
    icao: 'ZBAA',
    name: 'Sân bay Quốc tế Thủ Đô Bắc Kinh',
    city: 'Bắc Kinh',
    country: 'Trung Quốc',
    lat: 40.0799,
    lon: 116.6031,
    timezone: 'Asia/Shanghai',
  },
  DXB: {
    iata: 'DXB',
    icao: 'OMDB',
    name: 'Sân bay Quốc tế Dubai',
    city: 'Dubai',
    country: 'UAE',
    lat: 25.2532,
    lon: 55.3657,
    timezone: 'Asia/Dubai',
  },
  DOH: {
    iata: 'DOH',
    icao: 'OTHH',
    name: 'Sân bay Quốc tế Hamad',
    city: 'Doha',
    country: 'Qatar',
    lat: 25.2731,
    lon: 51.6081,
    timezone: 'Asia/Qatar',
  },
  CDG: {
    iata: 'CDG',
    icao: 'LFPG',
    name: 'Sân bay Quốc tế Charles de Gaulle',
    city: 'Paris',
    country: 'Pháp',
    lat: 49.0097,
    lon: 2.5479,
    timezone: 'Europe/Paris',
  },
  FRA: {
    iata: 'FRA',
    icao: 'EDDF',
    name: 'Sân bay Frankfurt',
    city: 'Frankfurt',
    country: 'Đức',
    lat: 50.0379,
    lon: 8.5622,
    timezone: 'Europe/Berlin',
  },
  LHR: {
    iata: 'LHR',
    icao: 'EGLL',
    name: 'Sân bay London Heathrow',
    city: 'London',
    country: 'Vương Quốc Anh',
    lat: 51.4700,
    lon: -0.4543,
    timezone: 'Europe/London',
  },
  AMS: {
    iata: 'AMS',
    icao: 'EHAM',
    name: 'Sân bay Quốc tế Amsterdam Schiphol',
    city: 'Amsterdam',
    country: 'Hà Lan',
    lat: 52.3105,
    lon: 4.7683,
    timezone: 'Europe/Amsterdam',
  },
  SYD: {
    iata: 'SYD',
    icao: 'YSSY',
    name: 'Sân bay Quốc tế Sydney Kingsford Smith',
    city: 'Sydney',
    country: 'Úc',
    lat: -33.9399,
    lon: 151.1753,
    timezone: 'Australia/Sydney',
  },
  MEL: {
    iata: 'MEL',
    icao: 'YMML',
    name: 'Sân bay Melbourne',
    city: 'Melbourne',
    country: 'Úc',
    lat: -37.6690,
    lon: 144.8410,
    timezone: 'Australia/Melbourne',
  },
  SFO: {
    iata: 'SFO',
    icao: 'KSFO',
    name: 'Sân bay Quốc tế San Francisco',
    city: 'San Francisco',
    country: 'Hoa Kỳ',
    lat: 37.6213,
    lon: -122.3790,
    timezone: 'America/Los_Angeles',
  },
};

// Map theo mã ICAO
export const AIRPORTS_BY_ICAO: Record<string, AirportInfo> = Object.values(AIRPORTS).reduce((acc, airport) => {
  acc[airport.icao] = airport;
  return acc;
}, {} as Record<string, AirportInfo>);
